language: bash

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.7.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker pull skylothar/openresty-testsuite:latest

script:
  - docker-compose up

branches:
  only:
    - master
