openresty:
  image: skylothar/openresty-testsuite:latest
  container_name: lua-resty-jwt-tests
  volumes:
    - .:/lua-resty-jwt
  working_dir: /lua-resty-jwt
  command:
    - '/bin/sh'
    - '-c'
    - 'luarocks make lua-resty-jwt-dev-0.rockspec && prove -r t'
